### PR TITLE
Hide update badge for hidden mods

### LINKED ISSUE #553: Update notifications should not be shown for hidden mods
Mods button should not show the diamond on the button if the updatable mod is deliberately hidden (but may not be deliberately excluded from updates) or is a library and libraries are hidden.

Case in point: mods button showed a diamond for Fabric API, which is a library and I have libraries hidden on list.
Tested on 5.1.0-beta.4 for 1.19.3.

### PR DESCRIPTION
**Pull request by LostLuma**
Resolves #553, cleans up the updater code a little.

This includes the commit from #631 so these two PRs can coexist properly.

### CODE REVIEW

**Comment by Prospector** [comment]
originally, my intention was to have some sort of update indicator on the filters button & toggle button that sort of "guides" you to enable libraries so you can see they need updates still, but never got around to it. For now, I think this solution is good enough though as I plan on rewriting the entire Modrinth UI soon anyway and the new UI I have planned will make this way clearer.

**Comment by LostLuma** [comment]
As a player I can't say I'm really too interested in library updates unless they are required by a mod I'm also updating to be honest, so I hope there'll be a toggle for it if you do this.

**Comment by Prospector** [comment]
well, that's the thing, if the library updates it's probably going to be required by one of the mods. It seems like kinda a problem if a user thinks they're all up-to-date but are experiencing bugs or other problems that are the result of outdated libraries

**Comment by LostLuma** [comment]
I'd hope the mod actually updates the version of the library it requires so the game wouldn't launch, but I can see why that might be an issue sadly 🙁

**Comment by Prospector** [comment]
yeah, idk with the new UI I am planning it shouldn't be much of a problem. The idea is instead of toggling libraries, you would just have Mods and Libraries tabs at the top, so you could just see if there's an indicator on the library tab and then you'll know.

Perhaps also I could have some sort of "Skip update" button (and a "Skip all" button for the libraries panel) which will save the update's information to a file somewhere and not prompt you again until the *next* update, so if you don't wanna bother you can just dismiss them all.

**Comment by Prospector** [comment]
also thanks for your PRs!

**Comment by LostLuma** [comment]
You're welcome 🦫

**Pull request merged**
