### PR TITLE
New Sorting Type: Has Update

### LINKED ISSUE #682: [Feature Suggestion] Option to filter by "updatability"
As the title suggests, this would add a filtering option to only display mods that have an available update.

An alternate implementation could be done with another Sorting option, one that would bump mods with updates available to the top of the mod list.

The use case is for someone like me, whose eyes tend to skip over the small icon that indicates a mod can be updated.

### PR DESCRIPTION
**Pull request by dvitski**
Adds a new sorting type which orders mods with updates first.

I often find myself searching through the mods list for which mods need updates, and figured having a sort type for that could be useful.

### CODE REVIEW

**Comment by Keaton42** [comment]
How do you do this? The only options on my filter button are sort a-z / z-a and show / hide libraries

**Comment by gniftygnome** [comment]
> How do you do this? The only options on my filter button are sort a-z / z-a and show / hide libraries

You type "update" in the search and it finds the ones with updates ... and all the things that have the word update in their name or description...  :P

**Comment by Keaton42** [comment]
Oh thank you! Very useful :D

**Comment by Keaton42** [comment]
Turns out that out of my 595 mods listed by mod menu, none of them need an update!! Wowza!!

**Pull request merged**
