### PR TITLE
Added deprecated badge

### PR DESCRIPTION
**Pull request by YanisBft**
Can be useful for fabric api modules, as well as mods remade from scratch

### CODE REVIEW

**Comment by Prospector** [comment]
Hmm..perhaps although this means deprecated mods would need to be updated, which kinda goes against the idea of deprecation a bit

**Comment by YanisBft** [comment]
I was more thinking of mods given up, and restarted with a new name. Like imagine having a mod called "X", but it has been restarted as "X 2", so X should be marked as deprecated, even if it still works.
But anyway I think it would be useful for api modules

**Comment by Madis0** [comment]
Why not "outdated"? Easier to understand for the user.

**Comment by YanisBft** [comment]
@Prospector Should I close this or update it with the "outdated" idea? About your comment btw, adding modmenu:outdated to a fabric.mod.json would need an update exactly the same way as marking methods as "deprecated"

**Comment by Prospector** [comment]
Hmm.. I'm not sure. I'll try to make a decision tomorrow. Currently I'm still not sure about the usefulness of this.

**Comment by Prospector** [comment]
ok, I think I will end up merging this.

**Comment by Prospector** [comment]
@Yanis48 if you fix the conflict, I'll merge

**Comment by YanisBft** [comment]
@Prospector done

**Comment by Prospector** [comment]
Thanks!

**Pull request merged**
