### PR TITLE
Port 1.19.2 to 22w43a fixing #494

### PR DESCRIPTION
**Pull request by Bawnorton**
Modify `ButtonWidget` constructors to match new `ButtonWidget` constructor or implement builder
Replace `ClickableWidge#x/y` with `ClickableWidget#getX/Y()` and `ClickableWidget#setX/Y()`
Replace `net.minecraft.util.math.Matrix4f` with `org.joml.Matrix4f;`

### CODE REVIEW

**Comment by ghost** [comment]
I tried that version, but in-game there is no `Mods` button. Only from main menu.

**Comment by Bawnorton** [comment]
I missed it before but Mojang changed the game menu to include a grid that wraps the buttons. It works as expected now.

**Comment by jackassmc** [comment]
Looks good, thank you! Please test with the latest snapshot and add it to the supported Modrinth versions if it works.

**Comment by jackassmc** [comment]
@haykam821 could you test this on the latest snapshot? I'm on mobile at the moment.

**Comment by jackassmc** [comment]
> Looks good, thank you! Please test with the latest snapshot and add it to the supported Modrinth versions if it works.



> @haykam821 could you test this on the latest snapshot? I'm on mobile at the moment.

Nevermind, I'll merge and release this and test the latest snapshot later.

Thanks @Benjamin-Norton for the PR and @unit-a-user for the bug report!

**Comment by haykam821** [comment]
Sorry for the delay. This version does work on Minecraft snapshot 22w44a.

image

**Comment by jackassmc** [comment]
No problem! Thanks for checking!

**Pull request merged**
