### PR TITLE
Fix translation

### PR DESCRIPTION
**Pull request by HidroGaming**

### CODE REVIEW

**Review by YanisBft — APPROVED** [review]
Good translation! 🇫🇷

**Comment by HidroGaming** [comment]
> Good translation! 🇫🇷

Thanks !

**Comment by Redblueflame** [comment]
I'm not really sure about "Bibliothèques" for code libraries, I think that keeping it like that will make it more natural, and feel less "google translated"

**Comment by YanisBft** [comment]
> I'm not really sure about "Bibliothèques" for code libraries, I think that keeping it like that will make it more natural, and feel less "google translated"

It isn't google translated, "bibliothèques" is the right term in French for "libraries" in programming. I remember seeing this term in several IDEs, like Arduino

**Comment by Redblueflame** [comment]
Applications commonly use "Bibliothèques", but the dedicated press always uses "Libraries". I guess that Bibliothèques is ok, as it's what's defined in the dictionary as of today, with "programmathèque", lol

**Comment by NeusFear** [comment]
Would be nice to have this based on 1.17 if possible instead of 1.16

**Comment by HidroGaming** [comment]
> Would be nice to have this based on 1.17 if possible instead of 1.16

I will do it if you want 😀

**Comment by HidroGaming** [comment]
I do a new pull request ?

**Comment by HidroGaming** [comment]
And for translation : a "Librairie" is a place where we buy books (not the only)

**Comment by jackassmc** [comment]
> I do a new pull request ?

Yes, leave this one open and make a new one targeting the `1.17` branch.

**Comment by HidroGaming** [comment]
Done!

**Comment by jackassmc** [comment]
Thank you!

**Pull request merged**
