### PR TITLE
Rename th.json to th_th.json

### PR DESCRIPTION
**Pull request by NaiNonTH**
* Renamed th.json to th_th.json to make the Thai Language actually work.

### CODE REVIEW

**Comment by Jab125** [comment]
this will not work in the long run, as the @weblate bot adds the languages files automatically, so a better approach is to get someone who can modify weblate's configuration

**Review by Jab125 — CHANGES_REQUESTED** [review]
this will not work in the long run, as the @weblate bot adds the languages files automatically, so a better approach is to get someone who can modify weblate's configuration

**Comment by jackassmc** [comment]
Weblate doesn't support renaming translation files, but it will detect a rename.

It might be possible to configure Weblate to use non default names when generating new translation files but I don't know how. I think the best way to handle this is to initialize empty translation files for all languages.

The [Minecraft Wiki](https://minecraft.fandom.com/wiki/Language) lists the following langaues:
- af_za
- ar_sa
- ast_es
- az_az
- ba_ru
- bar
- be_by
- bg_bg
- br_fr
- brb
- bs_ba
- ca_es
- cs_cz
- cy_gb
- da_dk
- de_at
- de_ch
- de_de
- el_gr
- en_au
- en_ca
- en_gb
- en_nz
- en_pt
- en_ud
- en_us
- enp
- enws
- eo_uy
- es_ar
- es_cl
- es_ec
- es_es
- es_mx
- es_uy
- es_ve
- esan
- et_ee
- eu_es
- fa_ir
- fi_fi
- fil_ph
- fo_fo
- fr_ca
- fr_fr
- fra_de
- fur_it
- fy_nl
- ga_ie
- gd_gb
- gl_es
- haw_us
- he_il
- hi_in
- hr_hr
- hu_hu
- hy_am
- id_id
- ig_ng
- io_en
- is_is
- isv
- it_it
- ja_jp
- jbo_en
- ka_ge
- kk_kz
- kn_in
- ko_kr
- ksh
- kw_gb
- la_la
- lb_lu
- li_li
- lmo
- lol_us
- lt_lt
- lv_lv
- lzh
- mk_mk
- mn_mn
- ms_my
- mt_mt
- nds_de
- nl_be
- nl_nl
- nn_no
- no_no‌[JE only] nb_no‌[BE only]
- oc_fr
- ovd
- pl_pl
- pt_br
- pt_pt
- qya_aa
- ro_ro
- rpr
- ru_ru
- se_no
- sk_sk
- sl_si
- so_so
- sq_al
- sr_sp
- sv_se
- sxu
- szl
- ta_in
- th_th
- tl_ph
- tlh_aa
- tok
- tr_tr
- tt_ru
- uk_ua
- val_es
- vec_it
- vi_vn
- yi_de
- yo_ng
- zh_cn
- zh_hk
- zh_tw

**Comment by jackassmc** [comment]
Merged into 1.16, 1.17, 1.18 and 1.19. Thank you!

**Pull request merged**
