### PR TITLE
Only count non-library, root (without a parent) mods in the main menu count.

### PR DESCRIPTION
**Pull request by AlexIIL**
This also separates the number of mods and libraries into the mods menu.

Screenshot from 2020-02-06 23-40-27
Screenshot from 2020-02-06 23-37-25
(If the mod count fits in one line then it's shown in one line).

Technical changes:
* Change ModMenu.LIBRARY_MODS to a set from a list. (It only ever seemed to be used like a set, so this shouldn't affect anything other than performance).
* Change the mod count to only include root non-library mods. And exclude "minecraft".
* Split the mod list counts up into root mods, children, root libraries, and their children.

(Unlike #73 this keeps things simple by just limiting what is considered to be a mod - while this could be configurable I don't really see much point).

### CODE REVIEW

**Comment by Prospector** [comment]
Maybe make the "Showing" text a single line like `Showing 2/2 mods and 5/5 libraries` and omit children entirely? Basically just treat children as part of the parent mod.

Edit: Oh, I see that is what it does if there's enough room. I still think omitting children is fine because they're kinda unnecessary to see a count of imo. My main issue with 2 lines is how little padding there is between the search box and the text and the text and the list.

**Comment by Prospector** [comment]
Part of me likes the transparency with how it is now, as in what you see is literally what fabric loads, but on the other hand, I also see how this is way more intuitive for users.

**Comment by AlexIIL** [comment]
> ...and omit children entirely...

That would make sense. However would it then be a good idea to show child counts in the parent item itself? (Perhaps like this mockup)
Screenshot from 2020-02-07 13-21-43

> My main issue with 2 lines is how little padding there is between the search box and the text and the text and the list.

I only did this because it was easier to squish the two lines where only 1 should have gone, but it should be possible to move the rest of the screen's elements down instead?

> ...how this is way more intuitive for users.

Personally I tend to view this as a side effect of fabric having jar-in-jar functionality - there's little point in informing the user that they have ~40 mods if ~30 of them were included as part of a bigger jar. (Also I think being able to split things up into modules should be a mostly technical thing - and so should be hidden from users normally)

**Comment by Prospector** [comment]
Yeah, that mockup works for me, though I don't think there needs to be a comma and Mods and Libraries probably shouldn't be capitalized? If the screen is truly ever not wide enough for the text...I guess splitting onto 2 lines is fine, but I really do prefer the single line.

**Comment by AlexIIL** [comment]
Ok, I'll implement it properly :)

**Comment by AlexIIL** [comment]
> If the screen is truly ever not wide enough for the text...I guess splitting onto 2 lines is fine, but I really do prefer the single line.

Removing the `(142 Children)` part makes it *nearly* always fit, unless the window is shrunk down far enough that it really can't: (This is the minimum size the window can go without turning the gui scale down automatically)
image

**Comment by AlexIIL** [comment]
Would it be better to collapse the `5/5 mods` down to `5 mods` if the current search doesn't filter out any mods (and the same for children)?

**Comment by AlexIIL** [comment]
Ok, I've implemented the smaller text - although I've got the collapsed fractions implemented locally and I think it makes it look a lot better - can I push them too?
image

**Comment by Prospector** [comment]
Yup, looks good. One thing though, should we perhaps handle cases for like `1 mod` instead of `1 mods`? Though that opens up a rabbit hole of some languages having special plural cases for 2, 3, 4, etc.

**Comment by AlexIIL** [comment]
That's a good idea.

As for other languages you could wait until someone else opens an issue for them... while it would be correct for english, it sounds like a bit of a pain to implement any more than that now.

**Comment by Prospector** [comment]
You don't have to implement this if you don't want to as only handling English is good enough for now, but theoretically, wouldn't it be possible to have lang for like `modmenu.mods.x` where x is the number of mods, and if a language does not specify (!I18n.hasTranslation()) then it defaults to `modmenu.mods.plural` or something? That way any language could specify however many it needs. English would just have:

```
"modmenu.mods.1": "mod",
"modmenu.mods.plural": "mods"
```

but a language could have this if they wanted to

```
"modmenu.mods.1": "mod",
"modmenu.mods.2": "modz",
"modmenu.mods.3": "modo",
"modmenu.mods.4": "modx",
"modmenu.mods.plural": "mods"
```

And the same for libraries as well

**Comment by AlexIIL** [comment]
That seems reasonably simple, sure.

**Comment by Prospector** [comment]
thinking about it again, I guess in English 0 would also be `mods`.  Not sure how other languages handle the 0 case, I think Spanish treats zero as singular.

**Comment by AlexIIL** [comment]
Currently I'm thinking of using `a` for the default case - rather than explicitly giving it some meaning.

**Comment by AlexIIL** [comment]
Although I'm not sure what to do for `1/3` cases... that might be different in different languages.

**Comment by Prospector** [comment]
Hmm... I'd say go with the plurality of the 2nd count. 1/1 mod, 1/2 mods

**Comment by AlexIIL** [comment]
So would that make `0/1 mod` rather than `0/1 mods`? I feel like that should be pluralised?

**Comment by AlexIIL** [comment]
I do have some slight concerns though: are there any languages that repeat a pattern? For example doing something special for every xx2 (like 2,12,22,32,42,52, etc). Or maybe that would be best left until someone actually needs it?

(Although most of this feels like it should be put into a lib rather than special-cased in modmenu - languages have a lot of edge cases, and solving this sort of thing properly would probably be useful for a lot of things)

**Comment by Prospector** [comment]
Yeah, maybe it should be 0/1 mods. I'm sure some repeat a pattern, though at that point, as you said it becomes very difficult. This should be good for a good majority of cases. Thanks! I'll do 1 final review when I get back to my pc.

**Comment by Prospector** [comment]
Ended up centering it because I think it looks nicer

image

**Comment by Prospector** [comment]
I wonder--should Minecraft be omitted from the menu entirely? As in, no entry is added for it to the list?

**Comment by AlexIIL** [comment]
> Ended up centering it because I think it looks nicer

Yeah, that looks better. Is that code in a fork of this fork or just locally? (Or just in an image :p)

> Should Minecraft be omitted...

Erm, maybe. Hopefully everyone who actually uses mod menu already knows what it is, and what version they are running, so it could make sense to hide it completely, however unlike libraries it's unlikely to confuse anyone?

It might be useful to keep it for other reasons though? (I'm not sure of any, but it might make sense if mod menu ever showed dependency information or anything else that could show relations).

**Comment by Prospector** [comment]
> It might be useful to keep it for other reasons though

yeah, I even considered the idea of a mod wanting to add a config menu for vanilla

> Is that code in a fork of this fork or just locally?

locally, just pulled from your fork into my local

**Comment by AlexIIL** [comment]
> yeah, I even considered the idea of a mod wanting to add a config menu for vanilla

Ok, so perhaps just omitting it from the count should be enough then?

> locally, just pulled from your fork into my local

Ok, I've enabled `Edits from maintainers` if you want to push directly to this.

**Comment by Prospector** [comment]
Ok, done with my changes

**Pull request merged**
