### PR TITLE
[#394] Fix 1.14 crash - Double check sorting is not null.

### LINKED ISSUE #394: 1.14 version doesnt work
when i launch fabric 1.14 with modmenu and I click on "mods" Minecraft just crashes, anyone know a solution?

### PR DESCRIPTION
**Pull request by MagnusHJensen**
closes #394 
And fix typo issue.

### CODE REVIEW

**Comment by jackassmc** [comment]
Oh wow, well done! I can confirm that a config with `{"sorting": null}` causes the crash reported in https://github.com/TerraformersMC/ModMenu/issues/394#issuecomment-1059718948.

So this wasn't https://github.com/TerraformersMC/ModMenu/issues/128 because the fix for that actually was backported to 1.14 (see https://github.com/TerraformersMC/ModMenu/commit/21e041501a76ca74b04014a7289ac0fa9b53fe2e).

This issue is also present on the 1.15 branch, could you please port this fix there? 1.16 and higher reject invalid config values at load time so it's not a problem there.

Both 1.14 and 1.15 were before my time, @Prospector could you please handle merging and publishing this?

**Comment by jackassmc** [comment]
Please update `"modmenu.sorting.decending"` in `et_ee.json` and `ja_jp.json`.

**Comment by MagnusHJensen** [comment]
> Oh wow, well done! I can confirm that a config with `{"sorting": null}` causes the crash reported in [#394 (comment)](https://github.com/TerraformersMC/ModMenu/issues/394#issuecomment-1059718948).
> 
> So this wasn't #128 because the fix for that actually was backported to 1.14 (see [21e0415](https://github.com/TerraformersMC/ModMenu/commit/21e041501a76ca74b04014a7289ac0fa9b53fe2e)).
> 
> This issue is also present on the 1.15 branch, could you please port this fix there? 1.16 and higher reject invalid config values at load time so it's not a problem there.
> 
> Both 1.14 and 1.15 were before my time, @Prospector could you please handle merging and publishing this?

All done :D

**Comment by jackassmc** [comment]
I thought this was merged already, sorry for the delay!

**Pull request merged**
