### PR TITLE
Supplemented and improved Russian translation

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Felix14-v2** [comment]
I'm also worried about localization breaking down with every update... But it's not my fault, it's just Crowdin is set up... weirdly. Anyway, translation options should be suggested here: https://crowdin.com/project/mod-menu

Btw, @Prospector , can you add missed localization strings there?

**Comment by Prospector** [comment]
The Crowdin is super messed up and to be honest, I don't know how to fix it. I'll try to figure it out soon

**Comment by ghost** [comment]
I learned a long time ago what Crowdin is and almost immediately began to hate it. Missing lines appear late, and even a year can pass from the moment of proposals to the implementation of the translation. I help translate WTHIT using GH Pull Requests and gosh! It is much faster and more convenient and anyone can either correct the translation themselves or write a review... In any case, I suggest the translation using only GH Pull Request, and if it does not fit, I will delete my fork of the repository along with this pull request.

**Review by ghost — COMMENTED** [review]
<p>The translation is consistent with the original and more semantically correct.</p>

**Comment by Felix14-v2** [comment]
> Missing lines appear late

> a year can pass from the moment of proposals to the implementation of the translation

This isn't Crowdin's fault. Crowdin is just a tool, you just need to use it properly. If you set up it correctly, the translation will be automatically merged with your repository. Even more: there are some mods (based on [this](https://github.com/gbl/CrowdinTranslate) library) that do not contain lang files and load relevant localization dynamically.

**Comment by Prospector** [comment]
Crowdin seems to have a lot of issues with having a ton of different branches because it keeps losing translations every time we make a new branch. It is probably user error but frankly their interface is so awful and unintuitive, this should not be so hard.

**Comment by ghost** [comment]
I would not call this tool good. Using Crowdin I tried to help translate the official launcher, and there I see the same thing that I see on Mod Menu page on Crowdin. Most of the translation sentences either look like a machine translation or a schoolboy translation, which is not semantically correct. Really good offers on Crowdin are very rare.

The question remains. Should I delete this Pull Request? I'm not going to use Crowdin for translation help, I'm more comfortable with GH Pull Requests or even resource packs with correct translations...

**Comment by Felix14-v2** [comment]
> Most of the translation sentences either look like a machine translation or a schoolboy translation, which is not semantically correct

That's why proofreaders exist. 

> I'm more comfortable with GH Pull Requests

Me too, but I've run into people who destroyed translation quality with their PR's. Mod authors can't verify the translation quality themselves, and this is a big problem. Crowdsourcing generally solves this problem. PR's are good (and the only) solution for small projects, but when your userbase is big enough, open conversation works better.
Of course, I don't turn a blind eye to the issues with Crowdin, but I believe they can be effectively solved.

> The question remains. Should I delete this Pull Request?

If I where you, I wouldn't do that until translation issues are solved. In addition, I personally have a couple of improvements for your translation, which I have already tested with my local resource pack.
Anyway, even if this PR is merged, after some time the translations will be automatically overwritten by Crowdin translations. So... I don't think it makes much sense :)

**Pull request closed without merging**
